services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_LOCAL_PORT
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes: 
  mysql-db: 